name: Primordial Movement
favicon: null
layout_spectrum: 0.61511
typography_spectrum: 0.7421
title: Primordial Movement
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#bebebe'
    - '#494949'
    - '#81041b'
  brandStrength: 0.5
  lightness: 0.42683154344558716
  saturation: 0.7557604855392128
  rhythmicContrast: 0.33613656274974346
purpose: []
